### ISSUE TITLE
About the metrics

### ISSUE THREAD

**Issue by kikizan** [HiLab-git/DTC#8]
Hello！
The evaluation index I reproduced is one point lower than that in the paper,
do you know the reason？

**Comment by Luoxd1996** [comment]
Hi,
I am so sad to hear this news, in my experiments the results also have slight differences in 0.5% when using different PyTorch, CUDA, and GPU versions. In the original paper, all experiments were done on the same machine, but the details of the machine and software settings I have forgotten. In addition, some researchers tell me this task's result (obtained by many existing methods) is not very stable, due to the data is too small, I recommend you use some high-performance machine to do this task.
Best;
Xiangde.

**Comment by kikizan** [comment]
I got it, thank you for your answer！

**Comment by adigasu** [comment]
Hi,
can you share machine and software version, if you remember? That will be helpful to compare the machine-wise results.
Thanks!
